packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  prisma: true
  tos-crc64-js: true
  unrs-resolver: true
